devtools::install_github("boxuancui/DataExplorer", quiet=T,  upgrade="never")


#BD_2020<- rio::import("G:/Mi unidad/DOCUMENTOS/6.TESIS 2018/Codebook_FONDECYT_1170239/a59ce30bf3a72a8a6df4a71290f8c646e47aa994/BD_2020.dta", format="dta")

#estandarizamos los nombres de columnas
#copiar_nombres(data.frame(original = colnames(BD_2020), clean_names = colnames(janitor::clean_names(BD_2020))))
#BD_2020<-janitor::clean_names(BD_2020)

#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_
library(readr)
library(DataExplorer)

BD_2020_input2 <-haven::read_dta("BD_2020.dta", encoding = "latin1")
BD_2020_input <- readxl::read_excel("BD_2020_input.xlsx")
#BD_2020_input <- read_csv("BD_2020_input.csv")
#BD_2020_input <- readr::read_csv("BD_2020.csv")

#estandarizamos los nombres de columnas
#copiar_nombres(data.frame(original = colnames(BD_2020), clean_names = colnames(janitor::clean_names(BD_2020))))
library(magrittr)
library(dplyr)
cols <- c('n_persona','a2','a3','a4','a5','a6','a7','a8','a9','a10','a11','a12_o1','a12_o2','a12_o3','a12_o4',
          'a12_o5','a12_o6','a12_otra_1','a12_otra_2','a13','a14','a15','a16','a17','a18_top_1','a18_top_2',
          'a18_top_3','a18_top_4','a18_top_5','a18_top_6','a18_top_7','a18_top_8','a18_top_9','a18_top_10',
          'a19_top_1','a19_top_2','a19_top_3','a19_top_4','a20_1_top_1','a20_1_top_2','a20_1_top_3','a20_1_top_4',
          'a20_1_top_5','a20_1_top_6','a20_1_top_7','a20_1_top_8','a20_1_top_9','a20_1_top_10','a20_1_top_11',
          'a20_1_top_12','a20_2_top_13','a20_2_top_14','a20_2_top_15','a20_2_top_16','a20_2_top_17','a20_2_top_18',
          'a20_2_top_19','a20_2_top_20','a20_2_top_21','a20_2_top_22','a20_2_top_23','a20_2_top_24','a21','a21_1',
          'a23','a25','a27','a28','a29_01','a29_02','a29_1','a22','a24','a26','a30','a31_top_1','a31_top_2',
          'a31_top_3','a31_top_4','a31_top_5','a31_top_6','a31_top_7','a31_top_8','a31_top_9','a31_top_10',
          'a31_top_11','a31_top_12','a31_top_13','a31_top_14','a31_top_15','a31_top_16','a32','a33_coded_1',
          'a33_coded_2','a33_coded_3','a34_top_1','a34_top_2','a34_top_3','a34_top_4','a34_top_5','a34_top_6',
          'a34_top_7','a34_top_8','a34_top_9','a34_top_10','a35_top_1','a35_top_2','a35_top_3','a35_top_4',
          'a35_top_5','a35_top_6','a36','a37_1','a37_2','a37_3','a38_top_1','a38_top_2','a38_top_3','a38_top_4',
          'a38_top_5','a38_top_6','a38_top_7','a38_top_8','a38_top_9','a38_top_10','a38_top_11','a38_top_12',
          'a38_top_13','a38_top_14','a39_top_1','a39_top_2','a39_top_3','a39_top_4','a39_top_5','a39_top_6',
          'a39_top_7','a40','a41','a42','a43_top_1','a43_top_2','a43_top_3','a43_top_4','a43_top_5','a44','a45_o1',
          'a45_o2','a45_o3','a45_o4','a45_o5','a46_top_1','a46_top_12','a46_top_13','a47_top_1','a47_top_2',
          'a47_top_3','a47_top_4','a47_top_5','a47_top_6','a47_top_7','a48','a49','a50','a51_1','a51_2','a51_3',
          'a52','a54','a56','a55','a57_1','a63','a58','a59','a60','a61','a62','zona','gse','edux','ocux','edad',
          'tamano_de_la_empresa','a1x1_coded_1','a1x2_coded_1','a11_recod','a48a49','depre','estrechez','mujer',
          'psicotrop','frec_acos21_1','frec_acos_ecotest','testigo','k2_muyelevado','k2_elevado','prec1','prec2',
          'prec4','prec5','prec6','antiguedad','politrab','desempleo','trabdom','atpub','latdec_dic','prec8',
          'prec9','estabilidad','prec7','democ_dic','vul1','vul2','vul3','vul4','vul5','vul6','vul7','vul',
          'auditc','prec3r','aposoc1','aposoc2','aposoc3','aposoc4','aposoc5','aposoc6','aposoc_tot','tenpsi',
          'iso','salgen','climasex','culorg1','culorg2','culorg3','cultura','lid_des1','lid_des2','lid_des3',
          'lid_des4','lid_des5','lid_des6','lid_des7','lid_des8','lid_des9','lid_des10','lid_des11','lid_des12',
          'lid_des13','lid_des14','lid_des1_rec','lid_des2_rec','lid_des3_rec','lid_des4_rec','lid_des5_rec','lid_des6_rec','lid_des7_rec','lid_des8_rec',
          'lid_des9_rec','lid_des10_rec','lid_des11_rec','lid_des12_rec','lid_des13_rec','lid_des14_rec','naq1','naq2','naq3','naq4','naq5','naq6','naq7',
          'naq8','naq9','naq10','naq11','naq12','naq13','naq14','naq15','naq16','naq17','naq18','naq19','naq20','naq21','naq22',
          'naq1_rec','naq2_rec','naq3_rec','naq4_rec','naq5_rec','naq6_rec','naq7_rec','naq8_rec','naq9_rec','naq10_rec',
          'naq11_rec','naq12_rec','naq13_rec','naq14_rec','naq15_rec','naq16_rec','naq17_rec','naq18_rec','naq19_rec','naq20_rec',
          'naq21_rec','naq22_rec','naq_leyman','naq_my_e','naq_a','mas_horas','menos45','quieren_mas','prec3','prec','precr',
          'precr1','tamano','r1','r2','r3','r4','r5','r6','r7','e1','e2','e3','la_rec','lf_rec','lc_rec','lf_leyman',
          'la_leyman','lc_leyman','k6','s1','s2','s3','s4','s5','ocuprev','naq_r_af_rec','naq_r_ap_rec','naq_r_rt_rec',
          'naq_af_leyman','naq_ap_leyman','naq_rt_leyman','naq_af_my_e','naq_ap_my_e','naq_rt_my_e','naq_af_a','naq_ap_a',
          'naq_rt_a','satlab_rec','araucaria_acoso','acoso_auto','acoso_auto_rec','naq_sum_roc','naq_sum_roc_3cat','hombre','autonaq','naq23',
          'naq24','naq23_rec','naq24_rec','naq_r_incivismo_rec','naq_inciv_leyman','prev3','superv','ocuprev_rec','sect_priv','cont_trab','org_sind','gse_ac3','jef_hogar','agr_fisica','acos_sex','lf_rec_logit','la_rec_logit',
          'lc_rec_logit','naq_dic_logit','lid_des_sum_cuartil','naq_sum_cuartil','expclass_culorg_1','expclass_culorg_2','expclass_culorg_3','expclass_culorg_4','expclass_culorg_5','expclass_culorg_6',
          'cluster_rec2','expclass_culorg_alt_1','expclass_culorg_alt_2','expclass_culorg_alt_3','expclass_culorg_alt_4','expclass_culorg_alt_5','expclass_culorg_alt_6','rec_expclass_culorg_alt_1','rec_expclass_culorg_alt_2','rec_expclass_culorg_alt_3','rec_expclass_culorg_alt_4',
          'rec_expclass_culorg_alt_5','rec_expclass_culorg_alt_6','rec_expclass_culorg_1','rec_expclass_culorg_2','rec_expclass_culorg_3','rec_expclass_culorg_4','rec_expclass_culorg_5','rec_expclass_culorg_6','lid_des_dic',
          'lid_des_dic_logit','bajarecompensa','altoesfuerzo','desbalance_dic','culorg1_ext','culorg2_ext','culorg3_ext','proc_res','bienst_tarea','laxo_estr','lid_des_my_e','cluster_rec2_binary','cluster_rec2_alt',
          'naq_sum_roc3','educacion277','ocuprev_xi_am277','ing_hog_xi_am277','vul_hm','lf_leyman_hm','la_leyman_hm','lc_leyman_hm','depre_hm',
          'psicotrop_hm','k2_elevado_hm','climasex_hm','jerarquia_acoso','jerarquia_acoso2','lid_des_leyman','acos_psico_freq','carga_dom','educacion_media',
          'cont_def','ocuprev_nocalif','santiago','valpo','concep','expclass_naq_alt_1','expclass_naq_alt_2','expclass_naq_alt_3',
          'expclass_naq_alt_4','expclass_naq_alt_5','expclass_naq_alt_6','rec_expclass_naq_alt_1','rec_expclass_naq_alt_2','rec_expclass_naq_alt_3','rec_expclass_naq_alt_4','rec_expclass_naq_alt_5','rec_expclass_naq_alt_6','cluster_rec2_naq_alt','turnos')
cols2 <- c("sbj_num","cluster_rec","cluster_alt","cluster_rec_alt","cluster_naq_alt","cluster_naq_alt_rec")

BD_2020_input2<- janitor::clean_names(BD_2020_input2) 
BD_2020_input<- BD_2020_input %>%
  janitor::clean_names() 
BD_2020_input[cols] <- lapply(BD_2020_input[cols], factor)
BD_2020_input[cols2] <- lapply(BD_2020_input[cols2], as.character)

#_#_#_#_#_#_#_#_#_#_#_#_#
#procesed file
#BD_2020_input <- readr::read_csv("BD_2020.csv")
#_#_#_#_#_#_#_#_#_#_#_#_#

#Ahora defino el metaarchivo asociado
metadata(BD_2020_input)$name <- "FONDECYT_1170239 A Marzo 2020"
metadata(BD_2020_input)$description <- "Prevalencia, formas de manifestacion y factores facilitadores de la violencia laboral, y sus efectos en la salud mental en poblacion asalariada en Chile atendiendo desiqualdades sociales y de genero. Inv. Responsable Elisa Ansoleaga"
metadata(BD_2020_input)$creator <- "Andres Gonzalez Santa Cruz"
metadata(BD_2020_input)$datePublished <- "2020-03-24"
#revisar por la presencia de eso: ^^^
codebook::var_label(BD_2020_input) <- list(sbj_num= 'SbjNum',
                                           n_persona= 'A. ¿Cuántas personas de 20 o más años que trabajan en forma dependiente o asalariada, viven actualmente en esta vivienda?',
                                           a2= 'En la empresa u organización donde usted trabaja ¿Supervisa a empleados/as?',
                                           a3= '¿A qué actividad económica se dedica la org. en la que trabaja?',
                                           a4= '¿Usted trabaja para un organismo público o para una empresa privada?',
                                           a5= 'En este trabajo ¿Tiene contrato o acuerdo de trabajo escrito?',
                                           a6= '¿Qué tipo de contrato o acuerdo de trabajo tiene?',
                                           a7= 'Incluyéndose Ud ¿cuántas personas trabajan en su lugar de trabajo?',
                                           a8= 'Habitualmente en su trabajo principal, ¿cuántas hrs trabaja en la semana?',
                                           a9= '¿Usted desearía trabajar?',
                                           a10= 'Respecto a su horario de trabajo, ¿este es?',
                                           a11= 'Podría decir si la remuneración de su trabajo principal, es:',
                                           a12_o1= 'Puede decirnos ¿de qué depende la parte variable de sus remuneraciones?',
                                           a12_o2= 'Puede decirnos ¿de qué depende la parte variable de sus remuneraciones?',
                                           a12_o3= 'Puede decirnos ¿de qué depende la parte variable de sus remuneraciones?',
                                           a12_o4= 'Puede decirnos ¿de qué depende la parte variable de sus remuneraciones?',
                                           a12_o5= 'Puede decirnos ¿de qué depende la parte variable de sus remuneraciones?',
                                           a12_o6= 'Puede decirnos ¿de qué depende la parte variable de sus remuneraciones?',
                                           a12_otra_1= 'Puede decirnos ¿de qué depende la parte variable de sus remuneraciones?',
                                           a12_otra_2= 'Puede decirnos ¿de qué depende la parte variable de sus remuneraciones?',
                                           a13= '¿Puede decirnos cuánto tiempo lleva trabajando en esta empresa u organización?',
                                           a14= 'Además del trabajo principal, ¿usted destina tiempo a otro trabajo pagado?',
                                           a14_1= '¿Cuántas horas le dedica a la semana en total a este otro trabajo pagado?',
                                           a15= 'En los últimos 12 meses ¿usted ha estado desempleado?',
                                           a15_1= 'En los últimos 12 meses, ¿Por cuánto tiempo ha estado desempleado?',
                                           a16= 'Sin considerar trabajo remunerado (semana), ¿dedica tiempo a tareas domésticas no remuneradas?',
                                           a16_1= 'Y aproximadamente, ¿Cuántas horas a la semana le dedica al trabajo doméstico y/o de cuidado en total?',
                                           a17= 'En su trabajo, ¿tiene habitualmente contacto directo con público, de viva voz o por teléfono (pacientes, clientes, alumnos, apoderados)?',
                                           a18_top_1= 'Mi trabajo exige que yo aprenda cosas nuevas (JCQ)',
                                           a18_top_2= 'Mi trabajo exige un alto nivel de calificaciones o habilidades (JCQ)',
                                           a18_top_3= 'Mi trabajo consiste en hacer siempre las mismas cosas (JCQ)',
                                           a18_top_4= 'Tengo libertad de decidir cómo hacer mi trabajo (JCQ)',
                                           a18_top_5= 'Tengo suficiente influencia en cómo ocurren las cosas en mi trabajo (JCQ)',
                                           a18_top_6= 'Mi trabajo exige trabajar muy rápido (JCQ)',
                                           a18_top_7= 'Me piden hacer una cantidad excesiva de trabajo (JCQ)',
                                           a18_top_8= 'Tengo suficiente tiempo para hacer mi trabajo (JCQ)',
                                           a18_top_9= 'Recibo demandas contradictorias por parte de otras personas (JCQ)',
                                           a18_top_10= 'Mi trabajo me exige un trabajo mental muy intenso (JCQ)',
                                           a19_top_1= '¿Hay en su trabajo momentos y/o situaciones que le producen desgaste emocional? (DEMOC)',
                                           a19_top_2= 'En general, ¿considera usted que su trabajo le produce desgaste emocional? (DEMOC)',
                                           a19_top_3= 'En su trabajo, ¿tiene usted que guardar sus emociones y no expresarlas? (DEMOC)',
                                           a19_top_4= 'En su trabajo, ¿tiene usted que guardar sus opiniones y no expresarlas? (DEMOC)',
                                           a20_1_top_1= 'Alguien le ha ocultado información que ha afectado a su rendimiento.(NAQ1)',
                                           a20_1_top_2= 'Ha sido humillado o ridiculizado en relación a su trabajo.(NAQ2)',
                                           a20_1_top_3= 'Le han ordenado realizar un trabajo que está por debajo de su nivel de competencia o calificación.(NAQ3)',
                                           a20_1_top_4= 'Le han cambiado de realizar tareas de responsabilidad por otras más triviales o desagradables.(NAQ4)',
                                           a20_1_top_5= 'Se han extendido rumores sobre usted.(NAQ5)',
                                           a20_1_top_6= 'Ha sido ignorado, excluido o le han dejado de hablar.(NAQ6)',
                                           a20_1_top_7= 'Le han insultado u ofendido con comentarios sobre usted, sus actitudes o su vida privada.(NAQ7)',
                                           a20_1_top_8= 'Le han gritado o ha sido objeto de enfados espontáneos.(NAQ8)',
                                           a20_1_top_9= 'Ha sufrido conductas intimidatorias como ser apuntado con el dedo, la invasión de su espacio personal, empujones, que no le dejen pasar, etc.(NAQ9)',
                                           a20_1_top_10= 'Ha visto detalles o indirectas de otros que le sugieran abandonar su trabajo.(NAQ10)',
                                           a20_1_top_11= 'Le han recordado continuamente sus errores y fallos.(NAQ11)',
                                           a20_1_top_12= 'Ha sido ignorado o ha recibido una reacción hostil cuando se ha acercado a alguien.(NAQ12)',
                                           a20_2_top_13= 'Ha recibido críticas persistentes sobre su trabajo y esfuerzo(NAQ13)',
                                           a20_2_top_14= 'Sus opiniones y puntos de vista han sido ignorados.(NAQ14)',
                                           a20_2_top_15= 'Ha recibido bromas pesadas de gente con la que no se lleva bien.(NAQ15)',
                                           a20_2_top_16= 'Le han asignado tareas u objetivos inalcanzables.(NAQ16)',
                                           a20_2_top_17= 'Ha recibido acusaciones (reclamos) en su contra.(NAQ17)',
                                           a20_2_top_18= 'Ha sido excesivamente supervisado en su trabajo.(NAQ18)',
                                           a20_2_top_19= 'Ha sido presionado para no reclamar algo a lo que tiene derecho (p. Ej., licencia por enfermedad, vacaciones, viáticos, etc.)(NAQ19)',
                                           a20_2_top_20= 'Ha sido objeto de numerosas tomaduras de pelo y sarcasmos.(NAQ20)',
                                           a20_2_top_21= 'Ha sido expuesto a una excesiva carga de trabajo.(NAQ21)',
                                           a20_2_top_22= 'Ha recibido amenazas de violencia o de abusos físicos.(NAQ22)',
                                           a20_2_top_23= 'Han dudado de su juicio sobre un asunto en el que tiene responsabilidad.',
                                           a20_2_top_24= 'Ha sido ignorado o excluido por el resto de sus compañeros o grupo profesional.',
                                           a21= 'Si definimos el acoso como una situación en la que una persona percibe que continuamente es objeto de conductas negativas frente a las cuales tiene dificultades para defenderse ¿según esta definición, usted ha sido acosado/a durante los últimos 6 mese',
                                           a21_1= 'Y, ¿qué tan frecuentemente ha ocurrido ese acoso?',
                                           a23= '¿Con qué frecuencia le ha ocurrido esto?',
                                           a25= '¿Con qué frecuencia le ha ocurrido esto?',
                                           a27= '¿Con qué frecuencia le ha ocurrido esto?',
                                           a28= '¿En los últimos 12 meses, en su trabajo principal ¿usted ha sido testigo de conductas, palabras o gestos de carácter sexual no deseado?',
                                           a29_01= 'Si usted ha sido objeto de acoso psicológico, agresión física o palabras o gestos de carácter sexual no deseados ¿Quiénes han sido principalmente los agresores?',
                                           a29_02= 'Si usted ha sido objeto de acoso psicológico, agresión física o palabras o gestos de carácter sexual no deseados ¿Quiénes han sido principalmente los agresores?',
                                           a29_1= '¿De qué sexo han sido los agresores?',
                                           a22= 'Ahora, si consideramos los últimos 12 meses, en su trabajo principal, ¿ha sido alguna vez objeto de acoso psicológico, es decir de palabras o actos repetidos que atacan su dignidad o integridad?',
                                           a24= '¿En su trabajo principal, en los últimos 12 meses, ha sido víctima de agresión física?',
                                           a26= 'En los últimos 12 meses, en su trabajo principal ¿ha sido objeto de palabras o gestos de carácter sexual no deseado?',
                                           a30= 'En caso de que usted haya sido objeto de alguna de las conductas señaladas, como acoso psicológico, agresión física o palabras o gestos de carácter sexual, ¿ha hecho algo para enfrentarlas?',
                                           a31_top_1= 'Evitar encontrarse con los/as agresores/as',
                                           a31_top_2= 'Hacer uso de licencias médicas',
                                           a31_top_3= 'Evitar pensar en los hechos',
                                           a31_top_4= 'Volcarse en otras actividades (deporte, salidas, recreación en general)',
                                           a31_top_5= 'Renunciar a su trabajo',
                                           a31_top_6= 'Buscar apoyo en las creencias religiosas o espirituales.',
                                           a31_top_7= 'Realizar planes para mejorar la situación y llevarlos a cabo.',
                                           a31_top_8= 'Buscar información para solucionar la situación.',
                                           a31_top_9= 'Comentar lo sucedido con sus compañeros/as de trabajo.',
                                           a31_top_10= 'Comentar lo sucedido con familiares y/o amigos/as',
                                           a31_top_11= 'Buscar ayuda en personas que sufren el mismo problema.',
                                           a31_top_12= 'Hablar con el/los involucrado/s',
                                           a31_top_13= 'Hablar con superiores.',
                                           a31_top_14= 'Denunciar los hechos al sindicato',
                                           a31_top_15= 'Tomar acciones legales',
                                           a31_top_16= 'Otras acciones',
                                           a32= 'Y ¿usted ha vivido alguna situación en la que hayan sido vulnerados o pasados a llevar sus derechos en el trabajo?',
                                           a33_coded_1= '¿Qué situación?, descríbala por favor.',
                                           a33_coded_2= '¿Qué situación?, descríbala por favor.',
                                           a33_coded_3= '¿Qué situación?, descríbala por favor.',
                                           a34_top_1= 'A menudo debido a la cantidad de tareas que tengo trabajo a un ritmo muy apurado (e1)',
                                           a34_top_2= 'Me interrumpen o molestan con frecuencia en mi trabajo (e2)',
                                           a34_top_3= 'En el último tiempo tengo cada vez más trabajo (e3)',
                                           a34_top_4= 'Mis superiores me dan el reconocimiento que merezco (r1)',
                                           a34_top_5= 'Las oportunidades de promoción en mi trabajo son escasas (r2)',
                                           a34_top_6= 'Me inquieta/angustia que se empeoren mis condiciones de trabajo (horario, carga laboral, salario, etc.) (r3)',
                                           a34_top_7= 'Mi estabilidad laboral es baja (r4)',
                                           a34_top_8= 'Si pienso en todo el trabajo y esfuerzo que he realizado, el reconocimiento que recibo en mi trabajo me parece adecuado (r5)',
                                           a34_top_9= 'Si pienso en todo el trabajo y esfuerzo que he realizado mis oportunidades de ascender me parecen adecuadas (r6)',
                                           a34_top_10= 'Si pienso en todo el trabajo y esfuerzo que he realizado, mi sueldo me parece adecuado (r7)',
                                           a35_top_1= 'Mi jefe inmediato presta atención a lo que yo digo (considera mi punto de vista)',
                                           a35_top_2= 'Mi jefe inmediato consigue que la gente trabaje junta',
                                           a35_top_3= 'Mi jefe inmediato facilita la realización del trabajo',
                                           a35_top_4= 'Los(as) colegas con quienes trabajo se interesan o preocupan por mí',
                                           a35_top_5= 'Mis colegas facilitan la realización de mi trabajo',
                                           a35_top_6= 'En mi trabajo tengo la impresión de formar parte de un equipo',
                                           a36= '¿En su lugar de trabajo hay un clima sexista?',
                                           a37_1= 'En mi empresa, (institución, organización) lo importante es cómo se hacen las cosas, no importan tanto los resultados.^^^En mi empresa, (institución, organización) lo importante son los resultados, no importa tanto cómo se hacen las cosas.',
                                           a37_2= 'En mi empresa, (institución, organización) se preocupan del bienestar de los trabajadores más que del cumplimiento de las tareas.^^^En mi empresa, (institución, organización) se preocupan del cumplimiento de las tareas más que del bienestar de los trabajad',
                                           a37_3= 'En mi empresa, (institución, organización) hay poca planificación y control, a veces hay que improvisar^^^En mi empresa, (institución, organización) hay una disciplina de trabajo muy estricta, todo está controlado y resulta predecible',
                                           a38_top_1= '¿Lo ha humillado a usted o a otros empleados/as, si no alcanzan los estándares esperados?(LID_DES1)',
                                           a38_top_2= '¿Ha incentivado las ideas o propuestas creativas o innovadoras?(LID_DES2)',
                                           a38_top_3= '¿Ha mostrado preocupación por los resultados?(LID_DES3)',
                                           a38_top_4= '¿Ha hecho gestos (por ejemplo, muecas, miradas, ademanes) a usted o a otros empleados para demostrar que no está satisfecho con su esfuerzo o el de los demás?(LID_DES4)',
                                           a38_top_5= '¿Ha evitado tomar decisiones?(LID_DES5)',
                                           a38_top_6= 'El supervisor/la supervisora ¿reconoce el buen desempeño?(LID_DES6)',
                                           a38_top_7= '¿Ha evitado involucrarse en su trabajo?(LID_DES7)',
                                           a38_top_8= '¿Ha difundido información incorrecta sobre usted o sus compañeros/as de trabajo, con el fin de dañar su posición o la de ellos en la empresa?(LID_DES8)',
                                           a38_top_9= '¿Ha estado ausente cuando se le/a necesita?(LID_DES9)',
                                           a38_top_10= '¿Le ha retado por teléfono, le colgó (cortó), o enviado un correo grosero porque pensó que había hecho un mal trabajo?(LID_DES10)',
                                           a38_top_11= '¿Busca la manera de desarrollar sus capacidades?(LID_DES11)',
                                           a38_top_12= '¿Establece objetivos claros e inequívocos?(LID_DES12)',
                                           a38_top_13= '¿Define y explica claramente las tareas que le asigna a usted y a sus compañeros de trabajo?(LID_DES13)',
                                           a38_top_14= '¿Es flexible y está dispuesto/a a pensar de manera innovadora?(LID_DES14)',
                                           a39_top_1= 'Tiene miedo de reclamar mejores condiciones de trabajo',
                                           a39_top_2= 'Se siente indefenso/a ante el trato injusto de sus superiores',
                                           a39_top_3= 'Se siente preocupado de que le cambien las condiciones de su salario',
                                           a39_top_4= 'Tiene miedo de que lo despidan si no hace lo que le piden',
                                           a39_top_5= 'Se siente preocupado(a) de que lo/a despidan o no le renueven el contrato',
                                           a39_top_6= 'Se siente preocupado por lo difícil que sería encontrar otro trabajo en caso que lo despidan',
                                           a39_top_7= 'Le hacen sentir que usted puede ser fácilmente reemplazado (a)',
                                           a40= '¿En su empresa o institución existe alguna organización sindical o gremial?',
                                           a41= 'Pertenece usted a alguna organización sindical o gremial',
                                           a42= '¿Tiene usted algún cargo de representación sindical?',
                                           a43_top_1= 'Me siento bastante satisfecho con mi trabajo actual (s1)',
                                           a43_top_2= 'Casi todos los días estoy entusiasmado con mi trabajo (s2)',
                                           a43_top_3= 'Cada día en el trabajo parece que nunca terminará (s3)',
                                           a43_top_4= 'Disfruto con mi trabajo (s4)',
                                           a43_top_5= 'Considero que mi trabajo es bastante desagradable (s5)',
                                           a44= 'En general, diría usted que su salud es…',
                                           a45_o1= 'En los últimos seis meses ¿ha enfrentado algunas de las siguientes situaciones?',
                                           a45_o2= 'En los últimos seis meses ¿ha enfrentado algunas de las siguientes situaciones?',
                                           a45_o3= 'En los últimos seis meses ¿ha enfrentado algunas de las siguientes situaciones?',
                                           a45_o4= 'En los últimos seis meses ¿ha enfrentado algunas de las siguientes situaciones?',
                                           a45_o5= 'En los últimos seis meses ¿ha enfrentado algunas de las siguientes situaciones?',
                                           a46_top_1= '¿Disminuir la ansiedad o el nerviosismo, tales como ansiolíticos? (CON_PSI)',
                                           a46_top_12= '¿Ayudar a dormir, tales como hipnóticos? (CON_PSI)',
                                           a46_top_13= '¿Remontar el ánimo tales como antidepresivos? (CON_PSI)',
                                           a47_top_1= 'Nervioso/a (K6)',
                                           a47_top_2= 'Desesperado/a (K6)',
                                           a47_top_3= 'Descontrolado/a o fuera de sí (K6)',
                                           a47_top_4= 'Tan deprimido/a que nada le puede hacer sonreír (K6)',
                                           a47_top_5= 'Que todo es un esfuerzo (K6)',
                                           a47_top_6= 'Bueno/a para nada (K6)',
                                           a47_top_7= 'Sin esperanza (K6)',
                                           a48= 'Durante los últimos 12 meses, ¿se sintió triste o deprimido/a por dos semanas consecutivas o más?',
                                           a49= 'Durante los últimos 12 meses, ¿llegó a sentir la pérdida de interés por la mayoría de las cosas que le gustaba hacer, tales como su trabajo, pasatiempos o cualquier actividad, por dos semanas seguidas o más?',
                                           a50= 'Si usted ha sentido alguno de los problemas de salud antes señalados, como sentirse nervioso/a o con miedo, triste, deprimido/a, o ha consumido algún medicamento ¿a qué lo/s atribuye?',
                                           a51_1= 'A continuación, quisiera hacerle algunas preguntas respecto a consumo de alcohol. ¿Qué tan seguido toma usted alguna bebida alcohólica?',
                                           a51_2= '¿Cuántos tragos suele tomar usted en un día típico de consumo de alcohol?',
                                           a51_3= '¿Qué tan seguido toma usted 5 o más tragos en una sola ocasión?',
                                           a52= 'Sexo',
                                           a53= 'Edad (años cumplidos)',
                                           a54= 'Indíqueme por favor, ¿cuál es su nivel educacional?',
                                           a56= 'Por favor, indíqueme el nivel educacional del jefe de hogar',
                                           a55= '¿Es usted el/la jefe/a de hogar?',
                                           a57_1= 'Jefe de Hogar:',
                                           a63= 'TRABAJO DEL ENTREVISTADO:',
                                           a58= '¿Nos podría decir en cuál de los siguientes tramos se encuentra su ingreso personal mensual? (considerando todos sus ingresos)',
                                           a59= 'Situación de pareja actual',
                                           a60= '¿Cuántas personas dependen económicamente de usted (totalmente o en parte)?',
                                           a61= 'Por favor, indique la frase que más se acerca a la realidad de su hogar: “Pensando en el total de ingresos mensuales de su hogar, este…',
                                           a62= '¿Me podría decir ¿en cuál de los siguientes tramos se encuentra aproximadamente el ingreso mensual total de su hogar?',
                                           weight= 'Weight (ponderador)',
                                           zona= 'Región (Adimark)',
                                           gse= 'GSE Encuestado/a (Adimark)',
                                           edux= 'Escolaridad (Adimark)',
                                           ocux= 'Situación Ocupacional (Adimark)',
                                           edad= 'Edad (en grupos) (Adimark)',
                                           tamano_de_la_empresa= 'Tamaño de la Empresa (Adimark)',
                                           a1x1_coded_1= 'Ocupación (Adimark)',
                                           a1x2_coded_1= 'Cargo (Adimark)',
                                           a11_recod= ' Podría decir si la remuneración de su trabajo principal, es: (Recodificado) (Adimark)',
                                           a48a49= 'Personas con síntomas depresivos (Adimark)',
                                           depre= 'Sintomatología depresiva',
                                           estrechez= 'Estrechez Económica',
                                           mujer= 'Sexo (1=Mujer)',
                                           psicotrop= 'Consumo de psicotrópicos',
                                           frec_acos21_1= 'Autocategorización Acoso Frecuente (Varias veces por semana y A diario)',
                                           frec_acos_ecotest= 'Presencia acoso psicologico Araucaria (A22)',
                                           testigo= 'Testigo de acoso sexual (A28)',
                                           k2_muyelevado= 'Distrés muy elevado (>12 en suma de puntajes brutos)',
                                           k2_elevado= 'Distrés elevado o muy elevado (>6)',
                                           k6_2= 'Suma de puntajes brutos Distrés K6',
                                           prec1= 'Ausencia Contrato Escrito',
                                           prec2= 'Contrato precario (Honorarios u otro)',
                                           prec4= 'Trabaja menos de 44 hrs y desea trabajar más',
                                           prec5= 'Horario nocturno o por turnos',
                                           prec6= 'Remuneración variable',
                                           antiguedad= 'Antigüedad (Mayor a 6 meses) (A13)',
                                           politrab= 'Politrabajo (A14)',
                                           desempleo= 'Desempleo últimos 12 meses (A15)',
                                           trabdom= 'Trabajo Doméstico (A16)',
                                           atpub= 'Atención a Público',
                                           khab= 'JCQ desarrollo de habilidades',
                                           kcont= 'JCQ control',
                                           latdec= 'JCQ latitud decisional',
                                           latdec_dic= 'Baja latitud decisional (Dicotomizada)',
                                           democ= 'Demandas Psicológicas (JCQ) y Demandas Emocionales (ISTAS 21)',
                                           prec8= 'Desempleo últimos 12 meses',
                                           prec9= 'Ingreso Personal Mensual (<350000 pesos)',
                                           estabilidad= 'Baja estabilidad laboral',
                                           prec7= 'Baja estabilidad laboral',
                                           democ_dic= 'Altas demandas emocionales (Dicotomizada)',
                                           vul1= 'Tiene miedo de reclamar mejores condiciones de trabajo',
                                           vul2= 'Se siente indefenso/a ante el trato injusto de sus superiores',
                                           vul3= 'Se siente preocupado de que le cambien las condiciones de su salario',
                                           vul4= 'Tiene miedo de que lo despidan si no hace lo que le piden',
                                           vul5= 'Se siente preocupado(a) de que lo/a despidan o no le renueven el contrato',
                                           vul6= 'Se siente preocupado por lo difícil que sería encontrar otro trabajo en caso que lo despidan',
                                           vul7= 'Le hacen sentir que usted puede ser fácilmente reemplazado (a)',
                                           vul= 'Vulnerabilidad, suma de puntajes (1= 3 o más)',
                                           auditc= 'Consumo riesgoso de Alcohol (ACC)',
                                           prec3r= 'Trabaja menos de 44 hrs y desea trabajar más',
                                           aposoc1= 'Mi jefe inmediato presta atención a lo que yo digo (considera mi punto de vista) (recodificada sin NR)',
                                           aposoc2= 'Mi jefe inmediato consigue que la gente trabaje junta (recodificada sin NR)',
                                           aposoc3= 'Mi jefe inmediato facilita la realización del trabajo (recodificada sin NR)',
                                           aposoc4= 'Los(as) colegas con quienes trabajo se interesan o preocupan por mí (recodificada sin NR)',
                                           aposoc5= 'Mis colegas facilitan la realización de mi trabajo (recodificada sin NR)',
                                           aposoc6= 'En mi trabajo tengo la impresión de formar parte de un equipo (recodificada sin NR)',
                                           aposoc_tot= 'Bajo apoyo social',
                                           tenpsi= 'JOBSTRAIN/Tensión Psíquica (Dicotomizada)',
                                           iso= 'ISOSTRAIN',
                                           salgen= 'Salud General (1=Mala o Muy Mala)',
                                           climasex= 'Clima Sexista',
                                           culorg1= 'CO orientada a Resultados (vs. a Procesos) (Art JPT)',
                                           culorg2= 'CO orientada a Cumplimiento de Tareas (vs. Bienestar de Trabajadores) (Art JPT)',
                                           culorg3= 'CO orientada a Control Estricto (vs. Laxo) (Art JPT)',
                                           cultura= 'C.O. Orientada a resultados, tareas y rígida',
                                           lid_des1= 'Variable LID_DES1 recodificada (sin datos perdidos)',
                                           lid_des2= 'Variable LID_DES2 recodificada (sin datos perdidos)',
                                           lid_des3= 'Variable LID_DES3 recodificada (sin datos perdidos)',
                                           lid_des4= 'Variable LID_DES4 recodificada (sin datos perdidos)',
                                           lid_des5= 'Variable LID_DES5 recodificada (sin datos perdidos)',
                                           lid_des6= 'Variable LID_DES6 recodificada (sin datos perdidos)',
                                           lid_des7= 'Variable LID_DES7 recodificada (sin datos perdidos)',
                                           lid_des8= 'Variable LID_DES8 recodificada (sin datos perdidos)',
                                           lid_des9= 'Variable LID_DES9 recodificada (sin datos perdidos)',
                                           lid_des10= 'Variable LID_DES10 recodificada (sin datos perdidos)',
                                           lid_des11= 'Variable LID_DES11 recodificada (sin datos perdidos)',
                                           lid_des12= 'Variable LID_DES12 recodificada (sin datos perdidos)',
                                           lid_des13= 'Variable LID_DES13 recodificada (sin datos perdidos)',
                                           lid_des14= 'Variable LID_DES14 recodificada (sin datos perdidos)',
                                           lid_des1_rec= 'Variable LID_DES1 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des2_rec= 'Variable LID_DES2 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des3_rec= 'Variable LID_DES3 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des4_rec= 'Variable LID_DES4 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des5_rec= 'Variable LID_DES5 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des6_rec= 'Variable LID_DES6 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des7_rec= 'Variable LID_DES7 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des8_rec= 'Variable LID_DES8 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des9_rec= 'Variable LID_DES9 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des10_rec= 'Variable LID_DES10 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des11_rec= 'Variable LID_DES11 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des12_rec= 'Variable LID_DES12 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des13_rec= 'Variable LID_DES13 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lid_des14_rec= 'Variable LID_DES14 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           lf= 'Suma de puntajes brutos Liderazgo Laissez-Faire (todas las variables)',
                                           la= 'Suma de puntajes brutos Liderazgo Autoritario',
                                           lc= 'Suma de puntajes brutos Liderazgo Constructivo (todas las variables)',
                                           naq1= 'Variable NAQ1 recodificada (sin datos perdidos)',
                                           naq2= 'Variable NAQ2 recodificada (sin datos perdidos)',
                                           naq3= 'Variable NAQ3 recodificada (sin datos perdidos)',
                                           naq4= 'Variable NAQ4 recodificada (sin datos perdidos)',
                                           naq5= 'Variable NAQ5 recodificada (sin datos perdidos)',
                                           naq6= 'Variable NAQ6 recodificada (sin datos perdidos)',
                                           naq7= 'Variable NAQ7 recodificada (sin datos perdidos)',
                                           naq8= 'Variable NAQ8 recodificada (sin datos perdidos)',
                                           naq9= 'Variable NAQ9 recodificada (sin datos perdidos)',
                                           naq10= 'Variable NAQ10 recodificada (sin datos perdidos)',
                                           naq11= 'Variable NAQ11 recodificada (sin datos perdidos)',
                                           naq12= 'Variable NAQ12 recodificada (sin datos perdidos)',
                                           naq13= 'Variable NAQ13 recodificada (sin datos perdidos)',
                                           naq14= 'Variable NAQ14 recodificada (sin datos perdidos)',
                                           naq15= 'Variable NAQ15 recodificada (sin datos perdidos)',
                                           naq16= 'Variable NAQ16 recodificada (sin datos perdidos)',
                                           naq17= 'Variable NAQ17 recodificada (sin datos perdidos)',
                                           naq18= 'Variable NAQ18 recodificada (sin datos perdidos)',
                                           naq19= 'Variable NAQ19 recodificada (sin datos perdidos)',
                                           naq20= 'Variable NAQ20 recodificada (sin datos perdidos)',
                                           naq21= 'Variable NAQ21 recodificada (sin datos perdidos)',
                                           naq22= 'Variable NAQ22 recodificada (sin datos perdidos)',
                                           naq1_rec= 'Variable NAQ1 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq2_rec= 'Variable NAQ2 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq3_rec= 'Variable NAQ3 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq4_rec= 'Variable NAQ4 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq5_rec= 'Variable NAQ5 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq6_rec= 'Variable NAQ6 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq7_rec= 'Variable NAQ7 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq8_rec= 'Variable NAQ8 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq9_rec= 'Variable NAQ9 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq10_rec= 'Variable NAQ10 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq11_rec= 'Variable NAQ11 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq12_rec= 'Variable NAQ12 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq13_rec= 'Variable NAQ13 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq14_rec= 'Variable NAQ14 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq15_rec= 'Variable NAQ15 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq16_rec= 'Variable NAQ16 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq17_rec= 'Variable NAQ17 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq18_rec= 'Variable NAQ18 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq19_rec= 'Variable NAQ19 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq20_rec= 'Variable NAQ20 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq21_rec= 'Variable NAQ21 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq22_rec= 'Variable NAQ22 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq_dic= 'Suma puntajes dicotomizado (NAQ) (Dichotomized sum score)',
                                           naq_leyman= 'NAQ Criterio Leymann',
                                           naq_my_e= 'NAQ Criterio Mikkelsen y Einarsen',
                                           naq_a= 'NAQ Criterio Agervold',
                                           mas_horas= 'Desearía trabajar más horas a la semana (A9)',
                                           menos45= 'Trabajo principal de menos 45 horas (A8)',
                                           quieren_mas= 'Desearía trabajar más horas a la semana (A9)',
                                           prec3= 'Trabaja menos de 45 horas semanales y desearia trabajar más',
                                           prec= 'Indicador de precariedad',
                                           precr= 'Indicador de precariedad',
                                           precr1= '3 o más indicadores de precariedad laboral (de suma prec1 2 3 5 6 7 8 y vul)',
                                           tamano= 'Tamaño de la organización (Adimark)',
                                           r1= 'Mis superiores me dan el reconocimiento que merezco',
                                           r2= 'Las oportunidades de promoción en mi trabajo son escasas',
                                           r3= 'Me inquieta/angustia que se empeoren mis condiciones de trabajo (horario, carga laboral, salario, etc.)',
                                           r4= 'Mi estabilidad laboral es baja',
                                           r5= 'Si pienso en todo el trabajo y esfuerzo que he realizado, el reconocimiento que recibo en mi trabajo me parece adecuado',
                                           r6= 'Si pienso en todo el trabajo y esfuerzo que he realizado mis oportunidades de ascender me parecen adecuadas',
                                           r7= 'Si pienso en todo el trabajo y esfuerzo que he realizado, mi sueldo me parece adecuado',
                                           e1= 'A menudo debido a la cantidad de tareas que tengo trabajo a un ritmo muy apurado',
                                           e2= 'Me interrumpen o molestan con frecuencia en mi trabajo',
                                           e3= 'En el último tiempo tengo cada vez más trabajo',
                                           esfuerzo= 'Suma Esfuerzos',
                                           recompensas= 'Suma Recompensas',
                                           la_rec= 'Suma ptjes dicotomizados Leyman (1,4,8,10) Lid Autoritario',
                                           lf_rec= 'Suma ptjes dicotomizados Leyman (5,7,9) Lid Laissez-Faire',
                                           lc_rec= 'Suma ptjes dicotomizados Leyman (6,11,12,14) Lid Constructivo',
                                           lf_leyman= 'Exposición a Lid. Laissez-Faire (Leymann)',
                                           la_leyman= 'Exposición a Lid. Autoritario/Tiránico (Leymann)',
                                           lc_leyman= 'Exposición a Lid. Constructivo (Leymann)',
                                           naq_sum= 'Acosados de vez en cuando o víctimas de acoso (Puntaje Bruto NAQ)',
                                           k6= 'Distrés elevado o muy elevado (>6)',
                                           s1= 'Me siento bastante satisfecho con mi trabajo actual',
                                           s2= 'Casi todos los días estoy entusiasmado con mi trabajo',
                                           s3= 'Cada día en el trabajo parece que nunca terminará',
                                           s4= 'Disfruto con mi trabajo',
                                           s5= 'Considero que mi trabajo es bastante desagradable (invertido)',
                                           satis= 'Suma de Puntajes Brutos Satisfacción Laboral',
                                           ocuprev= 'Ocupación Araucaria (codificada erroneamente, ver ocuprev rec)',
                                           naq_r_af_rec= 'Suma de puntajes dic (Al menos una vez a la semana) Acoso Físico',
                                           naq_r_ap_rec= 'Suma de puntajes dic (Al menos una vez a la semana) Acoso Psicológico',
                                           naq_r_rt_rec= 'Suma de puntajes dic (Al menos una vez a la semana) Rel con Trabajo',
                                           naq_af_leyman= 'NAQ Acoso Físico (Leymann)',
                                           naq_ap_leyman= 'NAQ Acoso Psicológico (Leymann)',
                                           naq_rt_leyman= 'NAQ Relacionado con el Trabajo (Leymann)',
                                           naq_af_my_e= 'NAQ Acoso Físico (Mikkelsen y Einarsen)',
                                           naq_ap_my_e= 'NAQ Acoso Psicológico (Mikkelsen y Einarsen)',
                                           naq_rt_my_e= 'NAQ Relacionado con el Trabajo (Mikkelsen y Einarsen)',
                                           naq_af_a= 'NAQ Acoso Físico (Agervold)',
                                           naq_ap_a= 'NAQ Acoso Psicológico (Agervold)',
                                           naq_rt_a= 'NAQ Relacionado con el Trabajo (Agervold)',
                                           satlab_rec= 'Baja Satisfacción Laboral (1er cuartil suma de puntajes)',
                                           araucaria_acoso= 'Suma acoso sexual, psicológico y físico, Araucaria',
                                           acoso_auto= 'Suma acoso sexual, psicológico y físico, Araucaria, más Autocategorización NAQ',
                                           acoso_auto_rec= 'Al menos una forma de victimización acoso sexual, físico, psi o autonaq',
                                           naq_sum_roc= 'Variable Dicotomizada Suma Puntajes Brutos NAQ Curvas ROC (>11 ptos) (tesis ags)',
                                           naq_sum_roc_3cat= 'Diferencia entre quienes obtienen >11 ptos, >9 ptos, y 0 a 8 (tesis ags)',
                                           hombre= 'Sexo Hombre (1=Hombre)',
                                           autonaq= 'Autocategorización según Definición NAQ (A21)',
                                           naq23= 'Variable NAQ23 recodificada (sin datos perdidos) no utilizada para cálculos indicadores NAQ',
                                           naq24= 'Variable NAQ24 recodificada (sin datos perdidos) no utilizada para cálculos indicadores NAQ',
                                           naq23_rec= 'Variable NAQ23 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq24_rec= 'Variable NAQ24 recodificada (sin datos perdidos en base a criterio Leymann)',
                                           naq_r_incivismo_rec= 'Escala Incivismo NAQ (Suma items 7, 14, 23 y 24) (Am y Xi 2018)',
                                           naq_inciv_leyman= 'Escala Incivismo NAQ (>0) (Am y Xi 2018)',
                                           prev3= 'Ocupación Araucaria (Operarios, Técnicos y No Calificados v/s Oficinistas, Servicios, Jefaturas y Profesionales) (Art JPT)',
                                           superv= 'Supervisa a otros',
                                           ocuprev_rec= 'Ocupación Araucaria (Recodificada 5= Vendedores) (Art JPT)',
                                           sect_priv= 'Trabaja Organismo Público o Empresa Privada (1=Sector privado)',
                                           cont_trab= 'Ausencia de Contrato Escrito (1= Sin Contrato)',
                                           org_sind= 'Existencia de Organización Sindical o Gremial (1=No)',
                                           gse_ac3= 'GSE Encuestado (D y E) (1= DyE)',
                                           jef_hogar= 'Jefe de Hogar (1=Sí)',
                                           agr_fisica= 'Agresión física últimos 12 meses',
                                           acos_sex= 'Acoso sexual últimos 12 meses',
                                           lf_rec_logit= 'Suma puntajes dicotomizados Lid Laissez-Faire Leymann (OCM), 3 niveles(ags)',
                                           la_rec_logit= 'Suma puntajes dicotomizados Lid Autoritario Leymann (OCM), 3 niveles(ags)',
                                           lc_rec_logit= 'Suma puntajes dicotomizados Lid Constructivo Leymann (OCM), 3 niveles(ags)',
                                           naq_dic_logit= 'Suma puntajes dicotomizados NAQ Leymann (OCM), 3 niveles(ags)',
                                           lid_des_sum= 'Suma puntajes brutos (5, 7, 9, 1, 4, 8, 10) Lid Destructivo',
                                           lid_des_sum_cuartil= 'NAQ por cuartiles (Por defecto, con 2000 casos)',
                                           naq_sum_cuartil= 'Suma ptjes brutos NAQ-R (por cuartiles) (correcto 1995 casos)',
                                           expclass_culorg_1= 'Pertenencia Esperada a la Clase 1 (>.5), Cultura por Clases (JPT)',
                                           expclass_culorg_2= 'Pertenencia Esperada a la Clase 2 (>.5), Cultura por Clases (JPT)',
                                           expclass_culorg_3= 'Pertenencia Esperada a la Clase 3 (>.5), Cultura por Clases (JPT)',
                                           expclass_culorg_4= 'Pertenencia Esperada a la Clase 4 (>.5), Cultura por Clases (JPT)',
                                           expclass_culorg_5= 'Pertenencia Esperada a la Clase 5 (>.5), Cultura por Clases (JPT)',
                                           expclass_culorg_6= 'Pertenencia Esperada a la Clase 6 (>.5), Cultura por Clases (JPT)',
                                           cluster_rec= 'Conjunto concatenado de clases (JPT)',
                                           cluster_rec2= 'Recodificación Clases Latentes Cultura (1=.;2=6;3=5;4=4;5=3;6=2;7=1) (JPT)',
                                           expclass_culorg_alt_1= 'Pertenencia Esperada a la Clase 1 (>.5), Cultura Alternativa por Clases (JPT)',
                                           expclass_culorg_alt_2= 'Pertenencia Esperada a la Clase 2 (>.5), Cultura Alternativa por Clases (JPT)',
                                           expclass_culorg_alt_3= 'Pertenencia Esperada a la Clase 3 (>.5), Cultura Alternativa por Clases (JPT)',
                                           expclass_culorg_alt_4= 'Pertenencia Esperada a la Clase 4 (>.5), Cultura Alternativa por Clases (JPT)',
                                           expclass_culorg_alt_5= 'Pertenencia Esperada a la Clase 5 (>.5), Cultura Alternativa por Clases (JPT)',
                                           expclass_culorg_alt_6= 'Pertenencia Esperada a la Clase 6 (>.5), Cultura Alternativa por Clases (JPT)',
                                           classprior1= 'Probabilidad A priori de Pertenecer a la Clase 1, CULTURA Definitiva por Clases (JPT)',
                                           classprior2= 'Probabilidad A priori de Pertenecer a la Clase 2, CULTURA Definitiva por Clases (JPT)',
                                           classprior3= 'Probabilidad A priori de Pertenecer a la Clase 3, CULTURA Definitiva por Clases (JPT)',
                                           classprior4= 'Probabilidad A priori de Pertenecer a la Clase 4, CULTURA Definitiva por Clases (JPT)',
                                           classprior5= 'Probabilidad A priori de Pertenecer a la Clase 5, CULTURA Definitiva por Clases (JPT)',
                                           classprior6= 'Probabilidad A priori de Pertenecer a la Clase 6, CULTURA Definitiva por Clases (JPT)',
                                           rec_expclass_culorg_alt_1= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura Alternativa, clase 1 (6 clases) (JPT)',
                                           rec_expclass_culorg_alt_2= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura Alternativa, clase 2 (6 clases) (JPT)',
                                           rec_expclass_culorg_alt_3= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura Alternativa, clase 3 (6 clases) (JPT)',
                                           rec_expclass_culorg_alt_4= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura Alternativa, clase 4 (6 clases) (JPT)',
                                           rec_expclass_culorg_alt_5= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura Alternativa, clase 5 (6 clases) (JPT)',
                                           rec_expclass_culorg_alt_6= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura Alternativa, clase 6 (6 clases) (JPT)',
                                           cluster_alt= 'Conjunto concatenado de clases definitivo (contiene a los que no pertenecen) (JPT)',
                                           cluster_rec_alt= 'Conjunto concatenado de clases definitivo (contiene a los que no pertenecen) (JPT)',
                                           rec_expclass_culorg_1= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura, clase 1 (6 clases) (JPT)',
                                           rec_expclass_culorg_2= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura, clase 2 (6 clases) (JPT)',
                                           rec_expclass_culorg_3= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura, clase 3 (6 clases) (JPT)',
                                           rec_expclass_culorg_4= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura, clase 4 (6 clases) (JPT)',
                                           rec_expclass_culorg_5= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura, clase 5 (6 clases) (JPT)',
                                           rec_expclass_culorg_6= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de Cultura, clase 6 (6 clases) (JPT)',
                                           naq_r_af_sum= 'Suma de puntajes brutos NAQ Acoso Físico (ags)',
                                           naq_r_ap_sum= 'Suma de puntajes brutos NAQ Acoso Psicológico (ags)',
                                           naq_r_rt_sum= 'Suma de puntajes brutos NAQ Acoso Relacionado con el Trabajo (ags)',
                                           democ_paper= 'Demandas Psicológicas (JCQ) y Demandas Emocionales (ISTAS 21) (ags)',
                                           lf2= 'Suma de puntajes brutos Liderazgo Laissez-Faire (solo variables validadas) (ags)',
                                           lc2= 'Suma de puntajes brutos Liderazgo Constructivo (solo variables validadas) (ags)',
                                           lid_des_dic= 'Suma puntajes dicotomizado (DLS) (Dichotomized sum score) (ags)',
                                           lid_des_dic_logit= 'Suma puntajes dicotomizados DLS Leymann (OCM), 3 niveles(ags)',
                                           bajarecompensa= 'Baja Recompensa (Art JPT)',
                                           altoesfuerzo= 'Alto Esfuerzo (Art JPT)',
                                           desbalance= 'esfuerzo/(recompensas* 0.4285)',
                                           desbalance_dic= 'Desbalance Esfuerzo-Recompensa',
                                           culorg1_ext= 'CO Desbalanceada en Eje Resultados vs. Procesos (puntajes 3 y 4=0)',
                                           culorg2_ext= 'CO Desbalanceada en Eje Control Estricto vs. Laxo (puntajes 3 y 4=0)',
                                           culorg3_ext= 'CO Desbalanceada en Eje Tareas vs. Bienestar Trabajadores (puntajes 3 y 4=0)',
                                           proc_res= 'CO Balanceada en Eje Resultados vs. Procesos (1=3/4) (JPT)',
                                           bienst_tarea= 'CO Balanceada en Eje Tareas vs. Bienestar Trabajadores (1=3/4) (JPT)',
                                           laxo_estr= 'CO Balanceada en Eje Control Estricto vs. Laxo (1=3/4) (JPT)',
                                           lid_des_my_e= 'Exposición a Liderazgos Destructivos (OCM Mikkelsen y Einarsen) (Art JPT)',
                                           cluster_rec2_binary= 'Clase a Comparar con el Resto de las Clases',
                                           classpost_culorg_alt1= 'Probabilidad Posterior de Pertencer a la Clase 1, CULTURA Definitiva por Clases (JPT)',
                                           classpost_culorg_alt2= 'Probabilidad Posterior de Pertencer a la Clase 2, CULTURA Definitiva por Clases (JPT)',
                                           classpost_culorg_alt3= 'Probabilidad Posterior de Pertencer a la Clase 3, CULTURA Definitiva por Clases (JPT)',
                                           classpost_culorg_alt4= 'Probabilidad Posterior de Pertencer a la Clase 4, CULTURA Definitiva por Clases (JPT)',
                                           classpost_culorg_alt5= 'Probabilidad Posterior de Pertencer a la Clase 5, CULTURA Definitiva por Clases (JPT)',
                                           classpost_culorg_alt6= 'Probabilidad Posterior de Pertencer a la Clase 6, CULTURA Definitiva por Clases (JPT)',
                                           cluster_rec2_alt= 'Clasificación por Cluster, Ítemes de Cultura (6 clases)',
                                           naq_sum_roc3= 'Suma ptjes brutos NAQ-R ROC (crit. inclusivo) (Art Xi y Am) (tesis ags)',
                                           educacion277= 'Recodificación de Nivel Educacional (Art. Ximena y Amalia)',
                                           ocuprev_xi_am277= 'Recodificación de Ocupación (Art. Ximena y Amalia)',
                                           ing_hog_xi_am277= 'Recodificación de Ingreso Hogar Mensual (Art. Ximena y Amalia)',
                                           vul_hm= 'Sólo con mujeres y hombres expuestos a vulnerabilidad (Art. Ximena y Amalia)',
                                           lf_leyman_hm= 'Sólo con mujeres y hombres expuestos a Lid Laissez Faire (Leymann) (Art. Ximena y Amalia)',
                                           la_leyman_hm= 'Sólo con mujeres y hombres expuestos a Lid Autoritario (Leymann) (Art. Ximena y Amalia)',
                                           lc_leyman_hm= 'Sólo con mujeres y hombres expuestos a Lid Constructivo (Leymann) (Art. Ximena y Amalia)',
                                           depre_hm= 'Sólo con mujeres y hombres expuestos a Sint Depresiva (Leymann) (Art. Ximena y Amalia)',
                                           psicotrop_hm= 'Sólo con mujeres y hombres expuestos a Cons Psicotrópicos (Leymann) (Art. Ximena y Amalia)',
                                           k2_elevado_hm= 'Sólo con mujeres y hombres expuestos a Distrés (Leymann) (Art. Ximena y Amalia)',
                                           climasex_hm= 'Sólo con mujeres y hombres expuestos a Clima Sexista (Leymann) (Art. Ximena y Amalia)',
                                           jerarquia_acoso= 'Expuestos a Acoso Psicológico, Físico o Sexual, Jerarquía Agresores (1)',
                                           jerarquia_acoso2= 'Expuestos a Acoso Psicológico, Físico o Sexual, Jerarquía Agresores (2)',
                                           lid_des_leyman= 'Exposición a Liderazgos Destructivos (OCM Leyman) (Art JPT)',
                                           acos_psico_freq= 'Acoso Psicológico Seguido y Muy Seguido (Art. Ximena y Amalia)',
                                           carga_dom= 'Y sin considerar su trabajo remunerado, durante la semana, ¿usted dedica además tiempo para hacer tareas domésticas y/o de cuidado, pero no remunerado? (A16)',
                                           educacion_media= 'Educación Menor a Nivel de Enseñanza Media Completa (Art. Magdalena)',
                                           cont_def= 'Contrato Definido (Art. Magdalena)',
                                           ocuprev_nocalif= 'Ocupación Sin Calificación (Operarios, Técnicos, Conductores y Trabajdores No-Calificados) (Art. Magdalena)',
                                           santiago= 'Zona, Gran Santiago',
                                           valpo= 'Zona, Gran Valparaiso',
                                           concep= 'Zona, Gran Concepción',
                                           classpost_naq_def_1= 'Probabilidad Posterior de Pertencer a la Clase 1, NAQ por Clases (ags)',
                                           classpost_naq_def_2= 'Probabilidad Posterior de Pertencer a la Clase 2, NAQ por Clases (ags)',
                                           classpost_naq_def_3= 'Probabilidad Posterior de Pertencer a la Clase 3, NAQ por Clases (ags)',
                                           classpost_naq_def_4= 'Probabilidad Posterior de Pertencer a la Clase 4, NAQ por Clases (ags)',
                                           classpost_naq_def_5= 'Probabilidad Posterior de Pertencer a la Clase 5, NAQ por Clases (ags)',
                                           classpost_naq_def_6= 'Probabilidad Posterior de Pertencer a la Clase 6, NAQ por Clases (ags)',
                                           expclass_naq_alt_1= 'Pertenencia Esperada a la Clase 1 (>.6), NAQ por Clases (ags)',
                                           expclass_naq_alt_2= 'Pertenencia Esperada a la Clase 2 (>.6), NAQ por Clases (ags)',
                                           expclass_naq_alt_3= 'Pertenencia Esperada a la Clase 3 (>.6), NAQ por Clases (ags)',
                                           expclass_naq_alt_4= 'Pertenencia Esperada a la Clase 4 (>.6), NAQ por Clases (ags)',
                                           expclass_naq_alt_5= 'Pertenencia Esperada a la Clase 5 (>.6), NAQ por Clases (ags)',
                                           expclass_naq_alt_6= 'Pertenencia Esperada a la Clase 6 (>.6), NAQ por Clases (ags)',
                                           rec_expclass_naq_alt_1= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de NAQ Definitiva, clase 1 (6 clases) (ags)',
                                           rec_expclass_naq_alt_2= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de NAQ Definitiva, clase 2 (6 clases) (ags)',
                                           rec_expclass_naq_alt_3= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de NAQ Definitiva, clase 3 (6 clases) (ags)',
                                           rec_expclass_naq_alt_4= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de NAQ Definitiva, clase 4 (6 clases) (ags)',
                                           rec_expclass_naq_alt_5= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de NAQ Definitiva, clase 5 (6 clases) (ags)',
                                           rec_expclass_naq_alt_6= 'Clase Esperada (sin 0), Clasificación por Cluster, Ítemes de NAQ Definitiva, clase 6 (6 clases) (ags)',
                                           cluster_naq_alt= 'Conjunto concatenado de clases definitivo (contiene a los que no pertenecen) NAQ (ags)',
                                           cluster_naq_alt_rec= 'Clasificación preliminar (contiene a los que no pertenecen) NAQ (ags)',
                                           cluster_rec2_naq_alt= 'Clasificación por Cluster, Ítemes de NAQ (6 clases)',
                                           turnos= 'Sistema de turnos')

BD_2020_input$educacion277<- factor(BD_2020_input$educacion277,labels=c("Sin Educacion o Basica", 
                                                                        "Media o Tecnica Incomp",
                                                                        "Tecnica Comp o Univ Incomp",
                                                                        "Universitaria Comp o Postgr"))
BD_2020_input$ocuprev_xi_am277<- factor(BD_2020_input$ocuprev_xi_am277,labels=c("Jef Intermedias", 
                                                                                "Prof y Tecnicos",
                                                                                "Emp Oficina y Vendedores",
                                                                                "Op, conductores y calif",
                                                                                "No calificados"))
BD_2020_input$ing_hog_xi_am277<- factor(BD_2020_input$ing_hog_xi_am277,labels=c("Hasta 540.000 pesos",
                                                                                "Desde 540.001 hasta 913.000 pesos",
                                                                                "Desde 913.001 o mas" ))
BD_2020_input$vul_hm<- factor(BD_2020_input$vul_hm,labels=c( "Vulnerable Mujer", "Vulnerable Hombre"))
BD_2020_input$lf_leyman_hm<- factor(BD_2020_input$lf_leyman_hm,labels=c( "Exp a Lid LF Mujer", "Exp a Lid LF Hombre"))
BD_2020_input$la_leyman_hm<- factor(BD_2020_input$la_leyman_hm,labels=c( "Exp a Lid Aut Mujer", "Exp a Lid Aut Hombre"))
BD_2020_input$lc_leyman_hm<- factor(BD_2020_input$lc_leyman_hm,labels=c( "Exp a Lid Cons Mujer", "Exp a Lid Cons Hombre"))
BD_2020_input$depre_hm<- factor(BD_2020_input$depre_hm,labels=c( "Exp a SintDep Mujer", "Exp a SintDep Hombre"))
BD_2020_input$climasex_hm<- factor(BD_2020_input$climasex_hm,labels=c( "Exp a ClimaSex Mujer", "Exp a ClimaSex Hombre"))
BD_2020_input$k2_elevado_hm<- factor(BD_2020_input$k2_elevado_hm,labels=c("Exp a Distres Mujer", "Exp a Distres Hombre"))
BD_2020_input$psicotrop_hm<- factor(BD_2020_input$psicotrop_hm,labels=c("Exp a ConsPsic Mujer", "Exp a ConsPsic Hombre"))
BD_2020_input$jerarquia_acoso<- factor(BD_2020_input$jerarquia_acoso,labels=c("Superiores", "Companeros", "Subalternos", "Externos"))
BD_2020_input$jerarquia_acoso2<- factor(BD_2020_input$jerarquia_acoso2,labels=c("Companeros", "Subalternos", "Externos"))

DataExplorer::create_report(BD_2020_input, 
              report_title= "Reporte de Resumen, Datos Exploratorios, Base de Datos Proyecto FONDECYT")